### PR TITLE
Declare license and copyright information using REUSE

### PR DESCRIPTION
**Pull request by msohn**
We now use https://reuse.software/ to declare license and copyright
information in a machine readable format.

The copyright statement for SAP open source projects was updated
to give credit to project contributors not employed by SAP.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
Same question as in https://github.com/gardener/cloud-provider-aws/pull/6#issuecomment-696697396

**Comment by msohn** [comment]
I thought I keep changes to the minimum since this is a fork of the upstream kubernetes/cloud-provider-azure

**Comment by msohn** [comment]
I now symlinked LICENSE like in the other repos

**Review by rfranzke — APPROVED** [review]
/lgtm

**Pull request merged**
